sudo: required
services:
    - docker

before_install:
    - docker build -t timbalimbs/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true timbalimbs/react-test npm test

after_success:
    - docker build -t timbalimbs/multi-client ./client
    - docker build -t timbalimbs/multi-nginx ./nginx
    - docker build -t timbalimbs/multi-server ./server
    - docker build -t timbalimbs/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push timbalimbs/multi-client
    - docker push timbalimbs/multi-nginx 
    - docker push timbalimbs/multi-server
    - docker push timbalimbs/multi-worker